apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: OBA-specs
  description: Specification foe Open Banking APIs
spec:
  type: service
  lifecycle: experimental
  owner: OBA
  providesApis:
    - Payment
    - Account
  consumesApis:
    - Payment
    - Account
